0616_final_410919954/0616_final_410919954/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _0616_final_410919954.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

0616_final_410919954/0616_final_410919954/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _0616_final_410919954.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Eaxm()
        {
            return View();
        }
    }
}

0616_final_410919954/0616_final_410919954/Controllers/VoiceController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _0616_final_410919954.Controllers
{
    public class VoiceController : Controller
    {
        public ActionResult Serach()
        { 
            return View();
        }


            [HttpPost]
        public ActionResult  Serach  (string name, string num)
        {
            if (name.IsNullOrWhiteSpace())
            {
                ViewBag.NameMes = "請輸入名字";
            }
            if (num.IsNullOrWhiteSpace())
            {
                ViewBag.NumMes = "請輸入數字";
            }

            if (!name.IsNullOrWhiteSpace() && !num.IsNullOrWhiteSpace())
            {
                ViewBag.Name = name;

                if (num == "1")
                {
                    ViewBag.Mes = "do";
                }
                else if (num == "2")
                {
                    ViewBag.Mes = "re";
                }
                else if (num == "3")
                {
                    ViewBag.Mes = "mi";
                }
                else if (num == "4")
                {
                    ViewBag.Mes = "fa";
                }
                else if (num == "5")
                {
                    ViewBag.Mes = "so";
                }
                else if (num == "6")
                {
                    ViewBag.Mes = "la";
                }
                else if (num == "7")
                {
                    ViewBag.Mes = "xi";
                }
                else
                {
                    ViewBag.Mes = "請輸入 1 - 7 之間的數！";
                }
            }
            return View();
        }
    }
}

0616_final_410919954/0616_final_410919954/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

0616_final_410919954/0616_final_410919954/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

0616_final_410919954/0616_final_410919954/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

0616_final_410919954/0616_final_410919954/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("連絡人", "Contact", "Home")</li>
                    <li>@Html.ActionLink("音符查詢", "Serach", "Voice")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> @DateTime.Now.Year - @DateTime.Now.Month / @DateTime.Now.Day</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

0616_final_410919954/0616_final_410919954/Views/Test/Eaxm.cshtml
<style>
    ol {
        list-style: none;
    }
</style>

@{
    ViewBag.Title = "Eaxm";
}

<h2>Exam</h2>

<p>姓名：莊婕榆 </p>
<p>學號：410919954 </p>

    @{ string[] fruits = { "蘋果", "香蕉", "荔枝", "鳳梨", "西瓜" }; }



    <ol>
        @{
            int i = 0;
            foreach (var item in fruits)
            {
                if (i < fruits.Length)
                {
                    <li> <p>@i : @item</p></li>
                }
                i++;
            }
        }
    </ol>

0616_final_410919954/0616_final_410919954/Views/Test/Exam.cshtml
<style>
    ol {
        list-style: none;
    }
</style>

@{
    ViewBag.Title = "Exam";
}

<h2>Exam</h2>

<p>姓名：莊婕榆 </p>
<p>學號：410919954 </p>

    @{ string[] fruits = { "蘋果", "香蕉", "荔枝", "鳳梨", "西瓜" }; }



    <ol>
        @{
            int i = 0;
            foreach (var item in fruits)
            {
                if (i < fruits.Length)
                {
                    <li> <p>@i : @item</p></li>
                }
                i++;
            }
        }
    </ol>

0616_final_410919954/0616_final_410919954/Views/Voice/Serach.cshtml
@{
    ViewBag.Title = "Serach";
}

<h2>音符查詢</h2>

@using (Html.BeginForm( "Serach", "Voice", FormMethod.Post))
{
    <p>姓名：@Html.TextBox("name")  @ViewBag.NameMes </p>
    <p>數字：@Html.TextBox("num")  @ViewBag.NumMes</p>
    <p>Hi， @ViewBag.Name ，查詢音符為：  @ViewBag.Mes </p>
    <input type="submit" value="送出">

}